package provider

import (
	"context"
	"strings"
)

type MockProvider struct{}

func NewMockProvider() *MockProvider {
	return &MockProvider{}
}

func (m *MockProvider) Chat(
	ctx context.Context,
	message string,
) (string, error) {

	msg := strings.ToLower(message)

	switch {
	case strings.Contains(msg, "hello"):
		return "Hello! How can I help you?", nil

	case strings.Contains(msg, "how are you"):
		return "I am a mocked LLM and doing great.", nil

	default:
		return "Mock response generated by Agent Gateway.", nil
	}
}
