package provider

import (
	"context"
	"fmt"
	"strings"

	"github.com/mayankanup/go-agent-gateway/internal/models"
)

type MockProvider struct{}

func NewMockProvider() *MockProvider {
	return &MockProvider{}
}

func (m *MockProvider) Chat(
	ctx context.Context,
	messages []models.Message,
) (string, error) {

	if len(messages) == 0 {
		return "No messages found.", nil
	}

	lastMessage :=
		messages[len(messages)-1].Content

	msg := strings.ToLower(lastMessage)

	switch {

	case strings.Contains(msg, "hello"):
		return "Hello! How can I help you?", nil

	case strings.Contains(
		msg,
		"what did i just say",
	):

		if len(messages) <= 2 {
			return "I don't know.", nil
		}

		previous :=
			messages[len(messages)-3].Content

		return fmt.Sprintf(
			"You previously said: %s",
			previous,
		), nil

	default:
		return "Mock response generated by Agent Gateway.", nil
	}
}
